#!/usr/bin/env bash

WORKDIR="~/.workdir"

workdir()
{
  dir=$(pwd)
  echo "$dir" > "$WORKDIR"
  echo "Work directory defined."
}

gotowork()
{
  if [ -f "$WORKDIR" ]; then
    dir=$(cat ~/.workdir)
    if [ -d "$dir" ]; then
      cd "$dir"
    else
      echo "Error: work directory does not exist. You must redefine it." >&2
    fi
  else
    echo "Error: work directory not defined." >&2
  fi
}

